name: Master Branch Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    name: Build APK
    steps:
      - name: Checking out repository
        uses: actions/checkout@v4
  
        # Set up JDK
      - name: Set Up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Change gradlew Permission
        run: chmod +x gradlew

        # Build App
      - name: Build with Gradle
        run: ./gradlew assemble

        
  lintCheck:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v4
        
      - name: Static Analysis
        run: ./gradlew lint
        
  pmd:
    name: PMD
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v4

      - name: PMD Check
        run: ./gradlew pmd
